# Generated by Django 5.0.14 on 2026-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_engine_oil_chain_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
    ]
